### ISSUE TITLE
Clicking on the "Graph" button doesn't show the graph window when it was minimized

### ISSUE THREAD

**Issue by yurivict** [rncbc/qjackctl#135]
How to reproduce:
1. Click "Graph"
2. Minimize the Graph window
3. Click on "Graph" again
4. The window doesn't show up

When the user clicks on "Graph" it should restore its original state and be in the foreground.

**Comment by rncbc** [comment]
when you minimize the Graph window you do that in the WM/DE context only; it stays as being shown up in the application side the button stays depressed, so that you probably need to click twice to bring it to show up again: first to really hide it and second to show up as normal.

one way to mitigate this is to check on Setup > Misc > Other > Keep child windows always on top; when enabled the "minimize" option is no more: case solved! :)

hyu.

**Comment by yurivict** [comment]
> [...] you probably need to click it twice to bring the window to show up once again [...]

This didn't work.


> one way to mitigate this is to check on Setup > Misc > Other > Keep child windows always on top option: when enabled the "Minimize" is no more: case solved! :)

This didn't work for me either.

-----------------------------

I think you need to use a Qt function that unminimizes the window so that it would be displayed in the foregrounf accorfing to the user intent.

**Comment by rncbc** [comment]
if it did not work then it is the (your) WM/DE that is ignoring it either way;
there is no such function or else it's the very same that shows up the window as normal, and that is already used since ever.

**Comment by yurivict** [comment]
Sorry, I got confused. It was "rolled-up", not minimized.
