### ISSUE TITLE
Connection in active Patchbay profile are not done automatically

### ISSUE THREAD

**Issue by pampelmuse76** [rncbc/qjackctl#137]
If only qjackctl ist started and jackd is not started via the "Start"-button,
and a midi keyboard is connected,
then the defined connection in the active profile in Patchbay is not done automatically.
See also:
https://bugzilla.redhat.com/show_bug.cgi?id=1943861

![qjackctl](https://user-images.githubusercontent.com/76697691/113507031-6cc58500-9548-11eb-9b90-089269f57af0.png)

>qjackctl --version
Qt: 5.15.2
JACK: 1.9.14
QjackCtl: 0.9.2

**Comment by rncbc** [comment]
you **must** start the jackd(bus)-audio server (status is "Started") _or_ have it already up and running when qjackctl is launched (and enters client mode; status is "Active").. otherwise the patchbay serves nothing, although it handles ALSA-MIDI connections too but that's just a convenience, not the _core business_ to qjackctl functionality, which is JACK.

**Comment by pampelmuse76** [comment]
I follow your arguments.
