### ISSUE TITLE
The FR manpage doesn't get installed

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qjackctl#26]

**Comment by rncbc** [comment]
carp! do you know why?

**Comment by trebmuh** [comment]
Not really. I'll try to investigate it later. Was just letting you know when encountered, for this info not to get lost.
Will keep you updated.

**Comment by mttvn** [comment]
It seems that the manpage for a specific language has to be in a specific folder inside the man folder.
For example, 
`/usr/local/share/man/fr/man1` instead of `/usr/local/share/man/man1.`

Moreover, it seems that the manpage should be named `qjackctl.1` for every language. It just has to be put in a different folder according to the language.

I have tried modifying the file `Makefile.in` for placing the French manpage inside the folder `man/fr/man1` as `qjackctl.1` and it works.

**Comment by trebmuh** [comment]
Note that it has been workarounded on the Debian packaging. See https://salsa.debian.org/multimedia-team/qjackctl/-/commit/cdd72ae36ab1861fb809acc93d184435cde39a53 .
